### ISSUE TITLE
Setting up GitVersion fails on Ubuntu and Windows

### ISSUE THREAD

**Issue by coder2000** [GitTools/actions#11]
I receive the following issues when trying to install GitVersion in my build.

![Screenshot from 2019-12-25 10-26-23](https://user-images.githubusercontent.com/27944/71448421-3bcd9200-2701-11ea-8ae9-f71dcec7b4d1.png)
![Screenshot from 2019-12-25 10-26-52](https://user-images.githubusercontent.com/27944/71448422-3f611900-2701-11ea-9a1d-48b0043497d5.png)

**Comment by giuliov** [comment]
I solved by moving `actions/setup-dotnet@v1` after GitVersion

**Comment by arturcic** [comment]
@coder2000 currently the github agents have 3.0.100 sdk pre-installed, that's why @giuliov has installed the sdk with the setup-dotnet action. The latest version (5.1.3) of gitversion works on .net core 3.1. So you can use the soltion of @giuliov, or install version 5.1.2 that works on 3.0 or wait till the agents will have the 3.1.100 sdk pre-installed.
