### ISSUE TITLE
GitVersion6: GitVersion6 showconfig

### ISSUE THREAD

**Issue by damu9618** [GitTools/actions#1200]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

We are using git version 6 latest for our azure devops pipelines  to show our config in the pipelines 
- task: gitversion/execute@0
  displayName: Show GitVersion config
  inputs:
    useConfigFile: true
    configFilePath: ${{ parameters.gitVersionConfigFilePath }}
    ${{ if eq(parameters.mainRepositoryName, '') }}:
      additionalArguments: /targetpath $(Build.SourcesDirectory) /showConfig
    ${{ else }}:
      additionalArguments: /targetpath $(Build.SourcesDirectory)/${{ parameters.mainRepositoryName }} /showConfig
      
      however this is started failing from version 6 where as it was working fine with previous version ex: 5.12.0
I have attached the complete log file for reference 
[116.txt](https://github.com/user-attachments/files/16359216/116.txt)

I have tried removing the /showconfig from the task then the logs were completely from the directory which was not expected attached the same for reference 
[withoutshowconfig.txt](https://github.com/user-attachments/files/16359246/withoutshowconfig.txt)

Could you please help us incase if we miss something hear for version 6 

### What is expected?

We would expect as showconfig with version 5.12.0

### Steps to Reproduce

Please try to have the same way in azure devops pipelines and run the above task

**Comment by arturcic** [comment]
@damu9618 please also update to the latestx tasks

**Comment by arturcic** [comment]
The reason it fails for the `/showconfig` is because the `gitversion/execute` expects to get the GitVersion output variables as a json object, and then set the env vars from it. That is by design.

`/showconfig` is actually returning the configuration yaml file and not the json output variables. 

Maybe we need to have a move specific action that actually sets the env vars and keep the execute for any other commands

**Comment by damu9618** [comment]
Hi @arturcic Thanks for the update, However I still see the same issue with the same config as above. could you please me If need to change something after your new commit ?

**Comment by arturcic** [comment]
> task: gitversion/execute@0

this is version 0, please install the latest version which is 3, and then it should be task: gitversion/execute@3,

same for the setup

**Comment by damu9618** [comment]
Hi @arturcic  Thanks for the quick response. Please find the complete details below
Actually we are using **dotnet tool install $toolName --configfile $nugetConfigPath --tool-path $(Agent.ToolsDirectory)** tool install git. I could successfully able to install it and see the logs 
**Checking if 'GitVersion.Tool' is already installed...
The tool is not yet installed, installing now into tools directory '/azp/_work/_tool' using NuGet config 'Reptor/nuget.config'...
You can invoke the tool using the following command: dotnet-gitversion
Tool 'gitversion.tool' (version '6.0.0') was successfully installed.**
using v3 version
- task: gitversion/execute@3
displayName: Show GitVersion config
inputs:
useConfigFile: true
configFilePath: ${{ parameters.gitVersionConfigFilePath }}
${{ if eq(parameters.mainRepositoryName, '') }}:
additionalArguments: /targetpath $(Build.SourcesDirectory) /showConfig
${{ else }}:
additionalArguments: /targetpath {{ parameters.mainRepositoryName }} /showConfig

and my config file path is **ConfigFilePath: App/GitVersion.yml**
However now i am getting different issue attached the logs
[git-logs.txt](https://github.com/user-attachments/files/16424561/git-logs.txt)

Could you please help me to solve this issue?

**Comment by arturcic** [comment]
as you can see from the logs it cannot find the dotnet-gitversion and the reason is beacuse the 
`task: gitversion/setup@3` that you are not using to install the GitVersion.Tool, is setting an environment variable that is later used by the `execute` task. https://github.com/GitTools/actions/blob/1b6eb626357cbaf7701cdc2ef54956e3b710d40d/src/tools/gitversion/tool.ts#L16

Another way would be to include the path where dotnet-gitversion is installed, to the $PATH environment variable
